= Starting project

This project provides the necessary to experiment tests based on living documentation.

You can find some description of the concept here: https://sfauvel.github.io/documentationtesting/

== Prerequisite

We use the library link:https://github.com/sfauvel/documentationtesting[documentationtesting]
which provides what we need to get started.
For a complete description of how to use it go to the link:https://sfauvel.github.io/documentationtesting/documentationtesting[documentation site]

The library is not yet on a public repository.
To use it, you need to download and install it.

You can download `.jar` and `.pom` from here:
link:https://github.com/sfauvel/documentationtesting/packages/538792?version=1.0[Documentation Testing 1.0]

Run this maven command to install it:
----
mvn install:install-file -Dfile=<path-to-file>.jar -DpomFile=<path-to-pomfile>.pom
----


[NOTE.speaker]
--
If needed, you may change library version editing properties in `pom.xml`.
----
<documentationtesting.version>1.0</documentationtesting.version>
----

--

== Quick start

To execute all run
----
mvn package
----

If all goes well, tests are executed and documentation is generated in `docs` folder.

== How to

=== Running test

You can run tests with `mvn test` or with your IDE.

We use the Golden Master technique.
Each test generates a file and compare the result to a reference file in `src/test/docs`.
If the content is the same, test pass, otherwise, test fails and the result file is saved in the same directory so we can compare it with reference file.

The reference file name ends with `.approved.adoc`.
It's name is built from class name and method name.
It's written in `link:https://asciidoctor.org/docs/what-is-asciidoc/[asciidoc]` format.

The file generated when test fails has the same name except that it ended with `.received.adoc`.
If `received` file is correct, you just have to rename it with `approved` to make it the new reference.

=== Generate documentation

There is one file created by file.
To group them into a single file, you can execute `main` in `DocGenerator` class.
It creates in `src/test/docs` an asciidoc file that includes all reference files.
This file is converted to an HTML file in ̀`docs` folder.

When you execute `mvn package`, this main program is launch after running tests.

=== Create a new test

To add a test, you just have to create a test as usual.

You need to add those line in your class.
[source, java]
----
DocWriter doc = new DocWriter();
@RegisterExtension
ApprovalsExtension extension = new ApprovalsExtension(doc);
----

`DocWriter` is the class used to record everything you want to write in your final document using `write` method.

An `ApprovalsExtension` have to be regsitered.
At the end of each test method, it checks if content written during test is identically to the reference file.

The first time you run a test, it fails bescause there is no reference file.
You have to adapt the `received` file to make it correspond to what you want and then,
rename it with `approved` instead of `received`.


Test name or @DisplayName content is used as chapter title in documentation.

The method Javadoc is written just under title in documentation.

=== Writing a test

Tests are a bit different from what we are used to.
There is no explicit assertion.
The verification is automatically done by the extension at the end of the test (@AfterEach).

*You should see a test method as a chapter writer more than a test*.
You are free to write anything you want to appear in your documentation.

There should be at least enough information to be able to take a decision on the behavior
and say whether or not it is compliant.

That means:

- Initial values
- Actions
- Result

