= Starting project

This project provides the necessary to experiment tests based on living documentation.

You can find some description of the concept in the https://sfauvel.github.io/documentationtesting/[DocumentationTesting site].

In this project, we use the https://sfauvel.github.io/documentationtesting/documentationtesting/[DocumentationTesting java library]
provides what we need to get started.

The library is not yet on a public repository but it's embedded in the project
so you don't have to worry with installation.
Nevertheless, you can download the link:https://github.com/sfauvel/documentationtesting/packages/538792[last Documentation Testing version] if needed.

== Quick start

After cloning the project, execute `prepare-package` goal to run all tests.
----
mvn prepare-package
----

If all goes well, tests are executed and documentation was generated in `docs` folder.

== How to

=== Running test

You can run tests with `mvn test` or with your IDE.

We use the https://en.wikipedia.org/wiki/Characterization_test[Golden Master] technique using https://approvaltests.com/[Approvals].
Each test generates a file and compare the result to a reference file located in `src/test/docs`.
if the contents of the files are the same, test will pass, otherwise, test fails.
In that case, the generated file is saved in the same directory so we can compare it with the reference file to identify the difference.

The reference file name ends with `.approved.adoc`.
It's name is built from class name and method name.
It's written in `link:https://asciidoctor.org/docs/what-is-asciidoc/[asciidoc]` format.

The file generated when test fails has the same name except that it ended with `.received.adoc`.
If you estimate that the `received` file describes the expected behavior, you just have to rename it replacing `received` with `approved`.
The file is now the new reference which ensures the non regression.

=== Generate documentation

There is one file created by test and one file created by test class.
Both end with `approved.adoc` and start with `\_`.
Files started by `_` will not be converted to html.

In this example, we generate another file without `_`, so this file will be converted to HTML.
It contains an `include` directive that include the `approved.adoc` file for the class.

When you execute `mvn package`, the `asciidoctor-maven-plugin`
will convert all files in `src/test/docs` that not start by `_` to HTML
and write them in `docs` folder at the root of the project.

=== Create a new test

To add a test, you just have to create a test as usual.

You need to add those line in your class.
[source, java]
----
@RegisterExtension
ApprovalsExtension doc = new SimpleApprovalsExtension();
----


An `ApprovalsExtension` have to be regsitered.
It's used to record everything you want to write in your final document using `write` method.
At the end of each test method, this extension checks if content written during test is the same as that of the reference file.

The first time you run a new test, it fails bescause there is no reference file.
You have to check the `received` file and updating it to match the expected behavior.
Then, rename it replacing `received` by `approved` to make it the new reference file.

Test name or `@DisplayName` annotation are used as chapter title in documentation.

The Javadoc of the method will be added in documentation just under the title.

=== Writing a test

Tests are a bit different from what we are used to.
There is no explicit assertion.
The verification is automatically done by the extension at the end of the test (@AfterEach).

*You should see a test method as a chapter writer more than a test*.
You are free to write anything you want to appear in your documentation.

There should be at least enough information to be able to take a decision on the behavior
and say whether or not it is compliant.

That means:

- Initial values
- Actions
- Result

