name: Publish doc
# V1.0
on:
  push:
    branches: [ publish_doc ]

  workflow_dispatch:

env:
  root_branch: 'master'
  doc_branch: 'pages'
  docs_generated: 'target/docs'
  docs_published: 'docs'
  release_pattern: 'documentationtesting-*'

jobs:
  check_prerequisites:
    name: Check the prerequisites
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{env.root_branch}}

      - name: check branch
        id: check_branch
        run: |
          NB_DOC_BRANCH=`git branch -r | grep "^\s*origin/${{env.doc_branch}}" | wc -l`
          echo "The branch ${{env.doc_branch}} must exist"
          echo "Nb branch ${{env.doc_branch}}: $NB_DOC_BRANCH"
          echo "::set-output name=NB_DOC_BRANCH::$NB_DOC_BRANCH"

    outputs:
      NB_DOC_BRANCH: ${{steps.check_branch.outputs.NB_DOC_BRANCH}}

  create_doc_branch:
    name: Create branch for documentation
    needs: check_prerequisites
    if: needs.check_prerequisites.outputs.NB_DOC_BRANCH == 0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{env.root_branch}}

      - name: Configure Git user
        run: |
          git config user.email "actions@noreply.github.com"
          git config user.name "GitHub Actions"

      - name: Create the branch
        run: |
          git checkout -b ${{env.doc_branch}}
          git push --set-upstream origin ${{env.doc_branch}}

  merge_from_root_branch:
    name: Merge from root branch
    needs: create_doc_branch
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{env.doc_branch}}

      - name: Configure Git user
        run: |
          git config user.email "actions@noreply.github.com"
          git config user.name "GitHub Actions"

      - name: Merge from root branch
        run: |
          git merge origin/${{env.root_branch}} --allow-unrelated-histories -m "Merge root branch"
          git push -f

  generate_doc:
    name: Generate doc
    needs: merge_from_root_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.doc_branch}}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install graphviz
        uses: kamiazya/setup-graphviz@v1

      - name: Package with Maven
        run: mvn -B package

  public_doc:
    name: Publish doc
    needs: generate_doc
    runs-on: ubuntu-latest
    steps:
      - name: Copy docs
        run: |
          rm -Rf ${{env.docs_published}}
          cp -R ${{env.docs_generated}} ${{env.docs_published}}

      - name: Retrieve diff
        id: git_diff
        run: |
          git add ${{env.docs_published}}
          echo "::set-output name=DOC_DIFF::$(git diff --cached  | wc -l)"
      #
      - name: Configure Git user
        if: steps.git_diff.outputs.DOC_DIFF > 0
        run: |
          git config user.email "actions@noreply.github.com"
          git config user.name "GitHub Actions"

      - name: Commit docs
        if: steps.git_diff.outputs.DOC_DIFF > 0
        run: |
          git add ${{env.docs_published}}
          git commit -m "New doc published"
          git push -f
